version: '2'
services:
  nginx:
    container_name: node-nginx-lb
    build: ./nginx
    volumes:
 - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - app-1:app-1
      - app-2:app-2
      - app-3:app-3
    ports:
      - 3000:80
      - 443:443
    depends_on:
      - app-1
      - app-2
      - app-3

  app-1:
    container_name: mock_1
    build: .
    volumes:
- ./home/kics/mockapp/mockdb:/src/db
ports:
      - 3000

  app-2:
    container_name: mock_2
    build: .
    volumes:
     - ./home/kics/mockapp/mockdb:/src/db
    ports:
      - 3000

  app-3:
    container_name: mock_3
    build: .
    volumes:
- ./home/kics/mockapp/mockdb:/src/db
    ports:
      - 3000

